/* IS NULL: check if a value is NULL or not */

/* For the following table CONTACTS, you allow the phone column to have NULL values */
CREATE TABLE contacts(
	id INT GENERATED BY DEFAULT AS IDENTITY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(255) NOT NULL,
	phone VARCHAR(15),
	PRIMARY KEY (id)
);

/* Insert two contacts, one w/ a phone number and the other without */
INSERT INTO contacts(first_name, last_name, email, phone)
VALUES ('John', 'Doe', 'john.doe@example.com', NULL),
	   ('Lily', 'Bush', 'lily.bush@example.com', '(408-234,2764)');

/* Find contact who does not have a phone numner */
SELECT
	id,
	first_name,
	last_name,
	email,
	phone
FROM
	contacts
WHERE
	phone = NULL;
/* returns no rows because expression phone = NULL in WHERE clause always returns false; this is
	because NULL is not equal to any value even itself */
	
/* To check whether a value is NULL or not, use the IS NULL operator instead:
	value IS NULL */
	
/* Use the following statement to get contact with no phone number */
SELECT id, first_name, last_name, email, phone
FROM contacts
WHERE phone IS NULL;

/* To check if a value is not NULL, use the IS NOT NULL operator:
	value IS NOT NULL */
SELECT id, first_name, last_name, email, phone
FROM contacts
WHERE phone IS NOT NULL;
