-- LIMIT: get a subset of rows generated by a query

/* LIMIT constrains the number of rows returned by the query.
	Syntax:
	SELECT select_list
	FROM table_name
	ORDER BY sort_expression
	LIMIT row_count
*/

/* The statement returns row_count rows. If row_count is zero, the query returns an empty
	set. If row_count is NULL, the query returns same result as if there wasn't a 
	LIMIT clause */

/* If you want to skip a number of rows before returning row_count rows, use OFFSET clause
	after LIMIT clause.
	Syntax:
		SELECT select_list
		FROM table_name
		LIMIT row_count OFFSET row_to_skip; */

/* Get first five films sorted by film_id */
SELECT
	film_id,
	title,
	release_year
FROM
	film
ORDER BY
	film_id
LIMIT 5;

/* Retrieve four films started from fourth one ordered by film_id */
SELECT
	film_id,
	title,
	release_year
FROM
	film
ORDER BY
	film_id
LIMIT 4 OFFSET 3;

/* Select top 10 most expensive films in rentals */
SELECT
	film_id,
	title,
	rental_rate
FROM
	film
ORDER BY
	rental_rate DESC
LIMIT 10;
	